# Generated by Django 5.1.1 on 2025-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverreceip',
            name='status',
            field=models.CharField(choices=[('Encargado', 'Encargado'), ('Procesando', 'Procesando'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Encargado', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('No pagado', 'No pagado'), ('Pagado', 'Pagado'), ('Parcial', 'Parcial')], default='No pagado', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Encargado', 'Encargado'), ('Procesando', 'Procesando'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Encargado', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='status_of_processing',
            field=models.CharField(choices=[('Encargado', 'Encargado'), ('Procesando', 'Procesando'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Encargado', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Encargado', 'Encargado'), ('Procesando', 'Procesando'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Encargado', max_length=100),
        ),
        migrations.AlterField(
            model_name='shoppingreceip',
            name='status_of_shopping',
            field=models.CharField(choices=[('No pagado', 'No pagado'), ('Pagado', 'Pagado'), ('Parcial', 'Parcial')], default='No pagado', max_length=100),
        ),
    ]
