# Generated by Django 5.1.1 on 2025-08-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_accountant',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_agent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_comunity_manager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_logistical',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('agent', 'Agente'), ('accountant', 'Contador'), ('buyer', 'Comprador'), ('logistical', 'Logístico'), ('community_manager', 'Community Manager'), ('admin', 'Administrador')], default='user', max_length=20),
        ),
    ]
