# Generated by Django 5.1.1 on 2025-11-01 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_deliverreceip_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverreceip',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Cliente al que pertenece el delivery', limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
