# Generated by Django 5.1.1 on 2025-11-03 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deliverreceip_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverreceip',
            name='order',
        ),
        migrations.AlterField(
            model_name='deliverreceip',
            name='client',
            field=models.ForeignKey(help_text='Cliente al que pertenece el delivery', limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
