# Generated by Django 5.1.1 on 2025-11-03 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_make_client_required_in_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverreceip',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría principal de los productos en este delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.category'),
        ),
    ]
