# Generated by Django 5.1.1 on 2025-10-06 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyingaccounts',
            options={'ordering': ['account_name'], 'verbose_name': 'Cuenta de Compra', 'verbose_name_plural': 'Cuentas de Compra'},
        ),
        migrations.AlterModelOptions(
            name='commoninformation',
            options={'verbose_name': 'Información Común', 'verbose_name_plural': 'Información Común'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='deliverreceip',
            options={'ordering': ['-deliver_date'], 'verbose_name': 'Recibo de Entrega', 'verbose_name_plural': 'Recibos de Entrega'},
        ),
        migrations.AlterModelOptions(
            name='evidenceimages',
            options={'ordering': ['-created_at'], 'verbose_name': 'Evidence Image', 'verbose_name_plural': 'Evidence Images'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paquete', 'verbose_name_plural': 'Paquetes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productbuyed',
            options={'ordering': ['-buy_date'], 'verbose_name': 'Producto Comprado', 'verbose_name_plural': 'Productos Comprados'},
        ),
        migrations.AlterModelOptions(
            name='productreceived',
            options={'ordering': ['-reception_date_in_eeuu'], 'verbose_name': 'Producto Recibido', 'verbose_name_plural': 'Productos Recibidos'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='shoppingreceip',
            options={'ordering': ['-buy_date'], 'verbose_name': 'Recibo de Compra', 'verbose_name_plural': 'Recibos de Compra'},
        ),
        migrations.AddField(
            model_name='buyingaccounts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buyingaccounts',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buying_accounts', to='api.shop'),
        ),
        migrations.AddField(
            model_name='buyingaccounts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commoninformation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commoninformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deliverreceip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deliverreceip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evidenceimages',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evidenceimages',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evidenceimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='amount_delivered',
            field=models.IntegerField(default=0, help_text='Cantidad total de productos entregados'),
        ),
        migrations.AddField(
            model_name='product',
            name='amount_purchased',
            field=models.IntegerField(default=0, help_text='Cantidad total de productos comprados'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productbuyed',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productbuyed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productreceived',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productreceived',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoppingreceip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shoppingreceip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('agent', 'Agente'), ('accountant', 'Contador'), ('buyer', 'Comprador'), ('logistical', 'Logístico'), ('community_manager', 'Community Manager'), ('admin', 'Administrador'), ('client', 'Cliente')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverreceip',
            name='deliver_picture',
            field=models.ManyToManyField(blank=True, to='api.evidenceimages'),
        ),
        migrations.AlterField(
            model_name='evidenceimages',
            name='public_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='package',
            name='number_of_tracking',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_picture',
            field=models.ManyToManyField(blank=True, to='api.evidenceimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pictures',
            field=models.ManyToManyField(blank=True, to='api.evidenceimages'),
        ),
        migrations.AlterField(
            model_name='productbuyed',
            name='observation',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreceived',
            name='observation',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
