# Generated by Django 5.1.1 on 2025-10-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_buyingaccounts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverreceip',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En transito', 'En transito'), ('Entregado', 'Entregado'), ('Fallida', 'Fallida')], default='Pendiente', max_length=100),
        ),
    ]
