# Generated by Django 5.1.1 on 2025-11-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_deliverreceip_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoninformation',
            name='change_rate',
            field=models.FloatField(default=0, help_text='Tasa de cambio de moneda (ej: USD a moneda local). Valor positivo requerido.'),
        ),
        migrations.AlterField(
            model_name='commoninformation',
            name='cost_per_pound',
            field=models.FloatField(default=0, help_text='Costo general de envío por libra en USD. Se usa para calcular costos de entrega.'),
        ),
    ]
