# Generated by Django 5.1.1 on 2025-10-10 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_delivery_status_enums'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Orden creada'), ('order_status_changed', 'Estado de orden cambiado'), ('order_assigned', 'Orden asignada'), ('order_completed', 'Orden completada'), ('order_cancelled', 'Orden cancelada'), ('product_added', 'Producto añadido'), ('product_purchased', 'Producto comprado'), ('product_received', 'Producto recibido'), ('product_delivered', 'Producto entregado'), ('product_out_of_stock', 'Producto agotado'), ('payment_received', 'Pago recibido'), ('payment_pending', 'Pago pendiente'), ('payment_overdue', 'Pago vencido'), ('package_shipped', 'Paquete enviado'), ('package_in_transit', 'Paquete en tránsito'), ('package_delivered', 'Paquete entregado'), ('package_delayed', 'Paquete retrasado'), ('user_registered', 'Usuario registrado'), ('user_verified', 'Usuario verificado'), ('user_role_changed', 'Rol de usuario cambiado'), ('system_message', 'Mensaje del sistema'), ('system_alert', 'Alerta del sistema'), ('system_maintenance', 'Mantenimiento del sistema')], max_length=50, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL de acción')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creada en')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Las notificaciones pueden expirar automáticamente', null=True, verbose_name='Expira en')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Orden creada'), ('order_status_changed', 'Estado de orden cambiado'), ('order_assigned', 'Orden asignada'), ('order_completed', 'Orden completada'), ('order_cancelled', 'Orden cancelada'), ('product_added', 'Producto añadido'), ('product_purchased', 'Producto comprado'), ('product_received', 'Producto recibido'), ('product_delivered', 'Producto entregado'), ('product_out_of_stock', 'Producto agotado'), ('payment_received', 'Pago recibido'), ('payment_pending', 'Pago pendiente'), ('payment_overdue', 'Pago vencido'), ('package_shipped', 'Paquete enviado'), ('package_in_transit', 'Paquete en tránsito'), ('package_delivered', 'Paquete entregado'), ('package_delayed', 'Paquete retrasado'), ('user_registered', 'Usuario registrado'), ('user_verified', 'Usuario verificado'), ('user_role_changed', 'Rol de usuario cambiado'), ('system_message', 'Mensaje del sistema'), ('system_alert', 'Alerta del sistema'), ('system_maintenance', 'Mantenimiento del sistema')], max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título agrupado')),
                ('count', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('aggregated_data', models.JSONField(default=list, verbose_name='Datos agregados')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_first', to='api.notification', verbose_name='Primera notificación')),
                ('last_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_last', to='api.notification', verbose_name='Última notificación')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_groups', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Grupo de notificaciones',
                'verbose_name_plural': 'Grupos de notificaciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_notification_types', models.JSONField(blank=True, default=list, help_text='Lista de tipos de notificación que el usuario desea recibir', verbose_name='Tipos de notificación habilitados')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Notificaciones push')),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Inmediato'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('never', 'Nunca')], default='immediate', max_length=20, verbose_name='Frecuencia de resumen')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificación',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notif_recip_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notif_recip_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recip_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notif_type_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='notif_priority_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'priority'], name='notif_unread_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notif_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='notif_content_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationgroup',
            index=models.Index(fields=['recipient', 'notification_type', '-updated_at'], name='api_notific_recipie_b9e888_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationgroup',
            index=models.Index(fields=['recipient', 'is_read'], name='api_notific_recipie_e7327c_idx'),
        ),
    ]
