# Generated by Django 5.1.1 on 2025-11-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_default_common_information'),
        ('api', '0006_alter_commoninformation_change_rate_and_more'),
    ]

    operations = [
    ]
