# Generated by Django 5.1.1 on 2025-11-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20251107_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='client_shipping_charge',
            field=models.FloatField(default=0, help_text='Cantidad que se le cobra al cliente por el envío por libra'),
        ),
    ]
