# Generated by Django 5.1.1 on 2025-10-10 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_observations_notification_notificationgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Agente asignado para este cliente', limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
