# Generated by Django 5.1.1 on 2025-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_client_shipping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingreceip',
            name='total_cost_of_purchase',
            field=models.FloatField(default=0, help_text='Costo total real de la compra (lo que se pagó efectivamente)'),
        ),
    ]
