# Generated by Django 5.1.1 on 2025-11-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_total_cost_of_purchase_to_shopping_receip'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_received',
            field=models.IntegerField(default=0, help_text='Cantidad total de productos recibidos'),
        ),
    ]
