# Generated by Django 5.1.1 on 2025-11-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_amount_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_value_of_client',
            field=models.FloatField(default=0, help_text='Cantidad total recibida del cliente por este pedido'),
        ),
    ]
