# Generated by Django 5.1.1 on 2025-10-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_product_description_alter_product_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='tax_rate',
            field=models.FloatField(default=0.0, help_text='Tasa de impuestos para esta tienda'),
        ),
    ]
