# Generated by Django 5.1.1 on 2025-11-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_received_value_of_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_tax',
            field=models.FloatField(default=0, help_text='IVA 7% calculado sobre (precio + envío)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_tax_amount',
            field=models.FloatField(default=0, help_text='Impuesto adicional calculado (3% o 5%)'),
        ),
    ]
