# Generated by Django 5.1.1 on 2025-11-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_base_tax_product_shop_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='charge_iva',
            field=models.BooleanField(default=True, help_text='Indica si se debe cobrar IVA (7%) para este producto'),
        ),
    ]
