# Generated by Django 5.1.1 on 2025-10-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_image_url_shop_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbuyed',
            name='order',
        ),
        migrations.AlterField(
            model_name='productbuyed',
            name='real_cost_of_product',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productbuyed',
            name='shoping_receip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyed_products', to='api.shoppingreceip'),
        ),
    ]
