# Generated by Django 5.1.1 on 2025-10-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_productbuyed_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Encargado', 'Encargado'), ('Comprado', 'Comprado'), ('Recibido', 'Recibido'), ('Entregado', 'Entregado')], default='Encargado', max_length=100),
        ),
    ]
