# Generated by Django 5.1.1 on 2025-11-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_charge_iva_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuyed',
            name='is_refunded',
            field=models.BooleanField(default=False, help_text='Indica si este producto comprado ha sido reembolsado'),
        ),
        migrations.AddField(
            model_name='productbuyed',
            name='refund_amount',
            field=models.FloatField(default=0, help_text='Monto del reembolso realizado'),
        ),
        migrations.AddField(
            model_name='productbuyed',
            name='refund_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se realizó el reembolso', null=True),
        ),
        migrations.AddField(
            model_name='productbuyed',
            name='refund_notes',
            field=models.TextField(blank=True, help_text='Notas sobre el reembolso', max_length=500, null=True),
        ),
    ]
