# Generated by Django 5.1.1 on 2025-10-24 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreceived',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto Recibido', 'verbose_name_plural': 'Productos Recibidos'},
        ),
        migrations.RemoveField(
            model_name='productreceived',
            name='amount_delivered',
        ),
        migrations.RemoveField(
            model_name='productreceived',
            name='deliver_receip',
        ),
        migrations.RemoveField(
            model_name='productreceived',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productreceived',
            name='package_where_was_send',
        ),
        migrations.RemoveField(
            model_name='productreceived',
            name='reception_date_in_cuba',
        ),
        migrations.RemoveField(
            model_name='productreceived',
            name='reception_date_in_eeuu',
        ),
        migrations.AddField(
            model_name='productreceived',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_products', to='api.package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status_of_processing',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Recibido', 'Recibido'), ('Procesado', 'Procesado')], default='Enviado', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreceived',
            name='amount_received',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productreceived',
            name='original_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiveds', to='api.product'),
        ),
        migrations.CreateModel(
            name='ProductDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception', models.DateField(blank=True, null=True)),
                ('amount_delivered', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliver_receip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_products', to='api.deliverreceip')),
                ('original_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivers', to='api.product')),
            ],
            options={
                'verbose_name': 'Producto Entregado',
                'verbose_name_plural': 'Productos Entregados',
                'ordering': ['-created_at'],
            },
        ),
    ]
