# Generated by Django 5.1.1 on 2025-11-14 14:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_productbuyed_is_refunded_productbuyed_refund_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio del periodo')),
                ('end_date', models.DateField(help_text='Fecha de fin del periodo')),
                ('expected_cost', models.DecimalField(decimal_places=2, help_text='Costo esperado para el periodo', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expected_profit', models.DecimalField(decimal_places=2, help_text='Ganancia esperada para el periodo', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo real del periodo (calculado automáticamente)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ganancia real del periodo (calculada automáticamente)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre este periodo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica Esperada',
                'verbose_name_plural': 'Métricas Esperadas',
                'ordering': ['-start_date', '-end_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='api_expecte_start_d_21d2bb_idx'), models.Index(fields=['-created_at'], name='api_expecte_created_f775dc_idx')],
            },
        ),
    ]
