# Generated by Django 5.1.1 on 2025-11-14 20:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_expectedmetrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectedmetrics',
            old_name='actual_cost',
            new_name='delivery_real_cost',
        ),
        migrations.RemoveField(
            model_name='expectedmetrics',
            name='actual_profit',
        ),
        migrations.RemoveField(
            model_name='expectedmetrics',
            name='expected_cost',
        ),
        migrations.RemoveField(
            model_name='expectedmetrics',
            name='expected_profit',
        ),
        migrations.AddField(
            model_name='expectedmetrics',
            name='others_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Otros costos del periodo (incorporados manualmente)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='expectedmetrics',
            name='range_delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo total de las entregas dentro del periodo.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='expectedmetrics',
            name='range_delivery_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso total de las entregas dentro del periodo.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='expectedmetrics',
            name='range_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ganancia total dentro del periodo', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='expectedmetrics',
            name='range_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ingresos totales dentro del periodo', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
