# Generated by Django 5.1.1 on 2025-10-31 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_productreceived_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de llegada del paquete'),
        ),
    ]
