# Generated by Django 5.1.1 on 2025-11-14 20:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_actual_cost_expectedmetrics_delivery_real_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedmetrics',
            name='delivery_real_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso real del periodo (calculado automáticamente)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
