# Generated by Django 5.1.1 on 2025-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_invoice_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverreceip',
            name='deliver_picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_pictures',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_picture',
        ),
        migrations.AddField(
            model_name='deliverreceip',
            name='deliver_picture',
            field=models.TextField(blank=True, help_text='JSON array of image URLs', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pictures',
            field=models.TextField(blank=True, help_text='JSON array of image URLs', null=True),
        ),
        migrations.DeleteModel(
            name='EvidenceImages',
        ),
        migrations.AddField(
            model_name='package',
            name='package_picture',
            field=models.TextField(blank=True, help_text='JSON array of image URLs', null=True),
        ),
    ]
