# Generated by Django 5.1.1 on 2025-11-18 14:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_deliverreceip_deliver_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectedmetrics',
            old_name='range_delivery_cost',
            new_name='registered_cost',
        ),
        migrations.RenameField(
            model_name='expectedmetrics',
            old_name='range_profit',
            new_name='registered_profit',
        ),
        migrations.RenameField(
            model_name='expectedmetrics',
            old_name='range_revenue',
            new_name='registered_revenue',
        ),
        migrations.RenameField(
            model_name='expectedmetrics',
            old_name='range_delivery_weight',
            new_name='registered_weight',
        ),
        migrations.RemoveField(
            model_name='expectedmetrics',
            name='delivery_real_cost',
        ),
        migrations.RemoveField(
            model_name='expectedmetrics',
            name='delivery_real_weight',
        ),
        migrations.RemoveField(
            model_name='expectedmetrics',
            name='others_costs',
        ),
        migrations.AddField(
            model_name='expectedmetrics',
            name='invoice_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo segun facturas', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='expectedmetrics',
            name='invoice_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso real segun facturas', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
