# Generated by Django 5.1.1 on 2025-11-19 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_range_delivery_cost_expectedmetrics_registered_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sales_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
