# Generated by GitHub Copilot - manual migration to add arrival_date to api_package
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_order_sales_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de llegada del paquete'),
            preserve_default=False,
        ),
    ]
