# Generated by Django 5.1.1 on 2025-11-23 01:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_is_reimbursable_from_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Envio', 'Envío'), ('Tasas', 'Tasas y cargos'), ('Sueldo', 'Sueldo'), ('Publicidad', 'Publicidad / Marketing'), ('Operativo', 'Gasto operativo'), ('Entrega', 'Entrega'), ('Otro', 'Otro')], default='Operativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='package',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de llegada del paquete'),
        ),
    ]
