# Generated by Django 5.1.1 on 2025-11-23 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_expense_category_alter_expense_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='account',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='shop',
        ),
    ]
