# Generated by Django 5.1.1 on 2025-11-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_migrate_product_pictures_to_url'),
        ('api', '0026_remove_expense_account_remove_expense_shop'),
    ]

    operations = [
    ]
