# Generated by Django 5.1.1 on 2025-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20251124_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdelivery',
            name='reception',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pictures',
            field=models.TextField(blank=True, help_text='image URLs', null=True),
        ),
    ]
