# Generated by Django 5.1.1 on 2025-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_productdelivery_reception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverreceip',
            name='deliver_picture',
            field=models.TextField(blank=True, help_text='image URLs', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_picture',
            field=models.TextField(blank=True, help_text=' image URL', null=True),
        ),
    ]
