# Generated by Django 5.1.1 on 2025-12-05 13:26

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_deliverreceip_deliver_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio del periodo')),
                ('end_date', models.DateField(help_text='Fecha de fin del periodo')),
                ('system_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso total de las entregas dentro del periodo.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('registered_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso total de las entregas dentro del periodo.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('revenues', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ingresos reales del periodo segun el registro', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('buys_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de compras dentro del periodo', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo total de las entregas dentro del periodo.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gastos totales dentro del periodo', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre este periodo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'ordering': ['-start_date', '-end_date'],
            },
        ),
        migrations.DeleteModel(
            name='ExpectedMetrics',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de pago'),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['start_date', 'end_date'], name='api_balance_start_d_2e2449_idx'),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['-created_at'], name='api_balance_created_7b9b45_idx'),
        ),
    ]
