# Generated by Django 5.1.1 on 2025-12-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_balance_delete_expectedmetrics_order_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingaccounts',
            name='account_name',
            field=models.CharField(max_length=100),
        ),
    ]
