# Generated by Django 5.1.1 on 2025-12-22 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_buyingaccounts_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Agente asignado para este cliente', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
