# Generated by Django 5.1.1 on 2026-01-13 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_customuser_assigned_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productbuyed",
            name="actual_cost_of_product",
        ),
        migrations.RemoveField(
            model_name="productbuyed",
            name="real_cost_of_product",
        ),
        migrations.AddField(
            model_name="productbuyed",
            name="quantity_refuned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shop",
            name="card_id",
            field=models.TextField(
                blank=True, help_text="Numero de tarjeta", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agente asignado para este cliente",
                limit_choices_to={"role__in": ["agent", "admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productbuyed",
            name="amount_buyed",
            field=models.IntegerField(default=0),
        ),
    ]
