# Generated by Django 5.1.1 on 2026-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_remove_productbuyed_actual_cost_of_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="card_id",
        ),
        migrations.AddField(
            model_name="shoppingreceip",
            name="card_id",
            field=models.TextField(
                blank=True, help_text="Numero de tarjeta", max_length=50, null=True
            ),
        ),
    ]
