# Generated by Django 5.1.1 on 2026-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_remove_shop_card_id_shoppingreceip_card_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_costs",
            field=models.FloatField(
                default=0,
                help_text="Costo total acumulado de todos los productos en la orden",
            ),
        ),
    ]
