# Generated by Django 5.1.1 on 2026-02-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_order_total_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverreceip",
            name="payment_status",
            field=models.BooleanField(
                default=False, help_text="True si la entrega está pagada, False si no"
            ),
        ),
    ]
