# Generated by Django 5.1.1 on 2026-02-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_alter_deliverreceip_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.FloatField(
                default=0,
                help_text="Saldo acumulado del cliente. Positivo = saldo a favor. Negativo = deuda pendiente. Se actualiza automáticamente con cada pago de pedido o entrega.",
            ),
        ),
    ]
