# Generated by Django 5.1.1 on 2026-03-11 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_add_balance_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverreceip',
            name='balance_applied',
            field=models.FloatField(default=0, help_text='Cantidad total de saldo del cliente aplicada como pago en esta entrega', verbose_name='Saldo aplicado'),
        ),
        migrations.AddField(
            model_name='order',
            name='balance_applied',
            field=models.FloatField(default=0, help_text='Cantidad total de saldo del cliente aplicada como pago en este pedido', verbose_name='Saldo aplicado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('agent', 'Agente'), ('accountant', 'Contador'), ('logistical', 'Logístico'), ('admin', 'Administrador'), ('client', 'Cliente')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='package',
            name='arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de llegada del paquete'),
        ),
    ]
