# Generated by Django 5.1.1 on 2026-09-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_deliverreceip_balance_applied_order_balance_applied_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='api_customuser_role_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverreceip',
            index=models.Index(fields=['status'], name='api_deliver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverreceip',
            index=models.Index(fields=['payment_status'], name='api_deliver_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverreceip',
            index=models.Index(fields=['-deliver_date'], name='api_deliver_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date'], name='api_expense_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='api_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pay_status'], name='api_order_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='api_order_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status_of_processing'], name='api_package_status_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['-arrival_date'], name='api_package_arrival_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='api_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='api_product_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingreceip',
            index=models.Index(fields=['-buy_date'], name='api_shopping_buy_date_idx'),
        ),
    ]
