
name = 'arye-shipps'
compatibility_date = "2024-09-23"
pages_build_output_dir = "apps/client/dist"

[build]
command = "cd apps/client && pnpm install && pnpm build"

# Variables de entorno para Pages
[env.production.vars]
VITE_APP_ENV = "production"