# Configuración para Cloudflare Pages
name = "ar-e-web-admin"
compatibility_date = "2024-10-07"

[env.production]
name = "ar-e-web-admin"

[env.development] 
name = "ar-e-web-admin-dev"

# Build configuration
[build]
command = "pnpm build"
cwd = "."
watch_dir = "src"

# Headers y redirects se manejan con _headers y _redirects en public/